[package]
name = "rusty-docker-compose"
version = "0.3.1"
edition = "2021"
authors = ["Jason Lee<lwlee2608@gmail.com>"]
description = "A Rust library to manage Docker Compose for integration testing, providing control over container lifecycles and logging."
license = "MIT"
